class_name LiteraryContent
extends RefCounted

static func _q(prompt: String, choices: Array, correct: int, explanation: String, author: String = "neutral") -> Dictionary:
	return {"question":prompt,"choices":choices,"correct":correct,"explanation":explanation,"author":author}

static func questions() -> Array[Dictionary]:
	return [
		_q("What does foreshadowing do?",["Prepares readers for a later event","Summarizes every earlier event","Explains a word's origin"],0,"An early clue can prepare a later development without revealing it outright."),
		_q("Which phrase is a metaphor?",["The room was cold","Her voice was a lantern","He ran like a fox"],1,"Calling a voice a lantern suggests guidance or warmth through a direct figurative comparison."),
		_q("Which detail is auditory imagery?",["A violet sky","The rough bark","A bell shivered through the fog"],2,"Auditory imagery evokes sound. Imagery can appeal to any sense."),
		_q("Dramatic irony occurs when…",["The audience knows more than a character","A poem has no rhyme","A character speaks loudly"],0,"Unequal knowledge can create suspense or comedy as the audience anticipates consequences."),
		_q("Which phrase uses alliteration?",["The pale moon","Briar branches bend","A candle in a window"],1,"The repeated initial /b/ sound connects the nearby words."),
		_q("What makes a narrator unreliable?",["Speaking in the first person","Being the main character","Giving reasons to doubt the account"],2,"Contradictions, bias, or limited understanding may lead readers to question a narrator."),
		_q("A symbol's meaning is best supported by…",["Its context and repeated uses","A universal dictionary of symbols","Its number of letters"],0,"Symbols acquire meaning through how a particular work uses them."),
		_q("Which action is close reading?",["Counting a book's pages","Examining how repeated words shape meaning","Guessing the ending from the cover"],1,"Close reading builds interpretations from specific textual details."),
		_q("Which conflict is internal?",["A sailor faces a storm","Two rivals compete","A character struggles with guilt"],2,"An internal conflict occurs within a character's thoughts, desires, or feelings."),
		_q("What is revision?",["Rethinking a draft's meaning and structure","Only fixing punctuation","Copying a final draft unchanged"],0,"Revision may change ideas, organization, evidence, and wording, as well as surface details."),
		_q("A narrative climax typically involves…",["A list of characters","Heightened tension or decisive action","The publisher's address"],1,"A climax concentrates a story's tension in a crucial moment or development."),
		_q("Catharsis is associated with…",["An alphabetical glossary","A change of narrator","Emotional release or clarification"],2,"In discussions of tragedy, catharsis concerns the audience's emotional experience."),
		_q("Which device repeats 'Nevermore' in The Raven?",["A refrain","A stage direction","A footnote"],0,"The recurring refrain takes on different implications as the speaker asks new questions.","poe"),
		_q("Why question the Tell-Tale Heart narrator?",["The story has no title","Claims of sanity clash with obsessive actions","The narrator is a detective"],1,"The contrast between the narrator's claims and described behavior supports an unreliable reading.","poe"),
		_q("Dupin is especially associated with…",["Pastoral farming","Courtly romance","Analytical detective work"],2,"Poe's Dupin stories helped establish conventions of detective fiction.","poe"),
		_q("The house in The Fall of the House of Usher parallels…",["The declining Usher family","A prosperous school","A political election"],0,"Physical decay links the setting to the family's deterioration.","poe"),
		_q("Who creates the Creature in Frankenstein?",["Robert Walton","Victor Frankenstein","Henry Clerval"],1,"Frankenstein is Victor's surname; the Creature is not given a personal name in the novel.","shelley"),
		_q("What frames much of Frankenstein's narrative?",["Newspaper advertisements","A courtroom verdict","Walton's letters"],2,"Walton's letters enclose Victor's narrative, which also includes the Creature's account.","shelley"),
		_q("A central question of Frankenstein concerns…",["Responsibility toward one's creation","How to win a royal election","The rules of cricket"],0,"Victor's abandonment of the Creature connects scientific ambition to ethical responsibility.","shelley"),
		_q("Henry Clerval often contrasts with Victor through…",["His ambition to become king","His interest in language and human connection","His rejection of all friendship"],1,"Clerval's interests and care offer an alternative to Victor's isolating obsession.","shelley"),
		_q("What can a soliloquy reveal?",["A book's print run","An editor's address","A character's private thinking"],2,"Soliloquies let audiences hear thoughts that other characters may not know.","shakespeare"),
		_q("Who causes confusion in A Midsummer Night's Dream?",["Puck","Darcy","Dupin"],0,"Puck's magical mistakes entangle the lovers and help drive the comedy.","shakespeare"),
		_q("Lady Macbeth's later speech especially reveals…",["A new interest in sailing","The effects of guilt","Perfect contentment"],1,"Her fragmented sleepwalking speech revisits images connected to the murders.","shakespeare"),
		_q("Prospero's control of events resembles…",["An accountant balancing figures","A farmer harvesting grain","A dramatist arranging a performance"],2,"The Tempest invites connections between Prospero's staging and theatrical creation.","shakespeare"),
		_q("Elizabeth Bennet learns to reconsider…",["Her first judgments of others","The spelling of her surname","Her ability to read"],0,"New evidence changes Elizabeth's understanding of Darcy and Wickham.","austen"),
		_q("Emma's matchmaking often shows…",["That she knows everyone's feelings perfectly","A gap between confidence and understanding","That the story has no conflict"],1,"Emma misreads others, making her growth depend partly on recognizing her own errors.","austen"),
		_q("Anne Elliot is the heroine of…",["The Tempest","Frankenstein","Persuasion"],2,"Persuasion follows Anne and Wentworth as they encounter a chance to renew their relationship.","austen"),
		_q("Elinor Dashwood's restraint suggests…",["Deep feeling may exist beneath a calm manner","She has no emotions","She never faces difficulty"],0,"Sense and Sensibility explores different ways of expressing and managing feeling.","austen"),
		_q("Who draws Alice toward Wonderland?",["The Raven","The White Rabbit","Prospero"],1,"Alice follows the White Rabbit and falls down the rabbit hole.","carroll"),
		_q("Treating Time as a person at the tea party is…",["A bibliography","A historical date","Personification"],2,"Personification gives human qualities to something nonhuman or abstract.","carroll"),
		_q("The Queen of Hearts' repeated threats satirize…",["Arbitrary authority","Patient scientific inquiry","Quiet friendship"],0,"Her extreme commands turn the exercise of power into absurdity.","carroll"),
		_q("The Cheshire Cat's vanishing grin challenges…",["The order of the alphabet","Ordinary physical logic","The existence of gardens"],1,"The grin without a cat makes a familiar expression into a literal impossibility.","carroll"),
		_q("Giving human qualities to a nonhuman thing is called…",["Foreshadowing","Personification","Alliteration"],1,"Personification lets an abstract or nonhuman subject act and feel like a person."),
		_q("Which best describes characterization?",["The order events are told","The physical setting of a scene","How a text reveals a character's traits"],2,"Characterization can work through action, speech, or the observations of other characters."),
		_q("Which phrase is a hyperbole?",["The sky was gray","She walked to the store","I've told you a million times"],2,"Hyperbole exaggerates deliberately; no reasonable reading takes the number literally."),
		_q("Which word is onomatopoeia?",["Chair","Buzz","Quickly"],1,"Onomatopoeic words imitate the sound of the thing they name."),
		_q("An allegory is best described as…",["A footnote citing a source","A narrative whose characters and events represent another meaning","A rhyme scheme"],1,"An allegory sustains a second, often abstract, layer of meaning across the whole narrative."),
		_q("Pathetic fallacy occurs when…",["A character lies to another character","A poem has no title","Nature or setting is given human emotion"],2,"A storm or a calm sky can mirror a character's mood through pathetic fallacy."),
		_q("A motif is…",["The book's dedication page","A single unrepeated image","A recurring element that reinforces a theme"],2,"A motif gathers meaning specifically through its repetition across a work."),
		_q("A frame narrative is…",["A story with no setting","A story enclosed within another story","A story with only one character"],1,"The outer story shapes how readers approach the story it encloses."),
		_q("Satire typically aims to…",["Provide a neutral summary","Avoid any humor","Criticize flaws through exaggeration or irony"],2,"Satire's exaggeration is usually corrective, not just comic."),
		_q("Juxtaposition places two elements together to…",["Combine them into one word","Hide one of them entirely","Sharpen understanding of both through contrast"],2,"Placing elements side by side highlights differences neither would show alone."),
		_q("Who narrates most Sherlock Holmes stories?",["Professor Moriarty","Inspector Lestrade","Dr. John Watson"],2,"Watson's narration shapes what readers notice about Holmes's methods.","doyle"),
		_q("Sherlock Holmes primarily solves cases through…",["Random chance","Careful observation and inference","Confessions obtained by force"],1,"Holmes reasons from small, overlooked details to a complete account.","doyle"),
		_q("Professor Moriarty is best described as…",["A loyal army doctor","A Scotland Yard inspector","A criminal mastermind who appears mostly through report"],2,"Moriarty dominates the story's late tension despite limited direct appearance.","doyle"),
		_q("In 'A Scandal in Bohemia,' Irene Adler is notable because she…",["Is Holmes's sister","Never appears in the story","Outwits Holmes's usual methods"],2,"Adler complicates the confidence readers place in Holmes's single method.","doyle"),
		_q("Tarzan is raised by…",["Wealthy relatives in London","Apes in the African jungle","Sailors on a merchant ship"],1,"His upbringing lets the novel question which of his traits are natural and which are learned.","burroughs"),
		_q("John Carter travels to which planet in A Princess of Mars?",["Venus","The Moon","Mars"],2,"Carter's arrival on Mars sets his Earth assumptions against an unfamiliar society.","burroughs"),
		_q("Dejah Thoris is best described as…",["Tarzan's childhood friend","A minor background character","A Martian princess and scientist"],2,"She drives the plot's stakes rather than only responding to them.","burroughs"),
		_q("Tars Tarkas belongs to which group in A Princess of Mars?",["Scotland Yard","The Tharks","The Baker Street Irregulars"],1,"Tarkas's loyalty complicates the Tharks' stated code of ruthlessness.","burroughs")
	]
